# Generated by Django 4.1.5 on 2023-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('answer_text', models.CharField(max_length=50)),
                ('thumbs_up_count', models.IntegerField(default=0)),
                ('thumbs_down_count', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
            ],
        ),
    ]
