# Generated by Django 4.1.5 on 2023-02-18 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0002_triviacategory_triviaquestion_trivia_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
